language: python
python:
  - "2.7"
# Removed until backoff is PY3 compatible
#  - "3.4"
install: pip install tox
script: tox
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email: false
